### ISSUE TITLE
Trainer Errors With Modern TrinityCore

### ISSUE THREAD

**Issue by Variona** [Nadromar/TrinityCreator#47]
Hello! I just started using this but I found an error where newer versions of TC cannot use the creature creator. The problem is the trainer section.

Four columns in particular: `trainer_type`, `trainer_spell`, `trainer_class`, and `trainer_race`. I'm not sure when these were removed from the database but I'm using TC rev. d12f0841f198 2019-01-07

Which is pretty recent as of this posting. It would be great if you could fix this. Thanks!

Example:
![image](https://user-images.githubusercontent.com/5630669/51391936-772f0c00-1b01-11e9-8e59-8a3810151237.png)

**Comment by Nadromar** [comment]
Seems a lot of the database structure changed, it'll be quite a bit of work to figure out what's what.
Fixed the issue you reported but it won't do much good since so much of the database structure needs to be updated. :/

Not making promises but maybe later today & tomorrow I'll put some time in making it 2019 compatible

**Comment by Nadromar** [comment]
Actually, could you help me out. I'm not testing against your version of the database.
And I don't quite feel like spending several hours prepping this PC for a fresh trinity compile.
I'd like you to send me the structure for the world database you're using.

I'll give you instructions for heidiSQL though you can use whichever tool you use as well.
1. Connect to the database with heidisql
2. Rightclick your world DB and click Export Database as SQL
3. Set Data: to No Data (so you don't export the entire world DB)
4. Select a file location and send me the file as an attachment to the reply.

Then i'll get it sorted for ya.

**Comment by Variona** [comment]
Yes, here you go. Not sure if I followed it correctly as the SQL file seems very unhelpful. Maybe I messed up exporting it?

[World_DB_TC_2019.zip](https://github.com/Nadromar/TrinityCreator/files/2776218/World_DB_TC_2019.zip)

Had to compress as .sql isnt uploadable.

**Comment by Nadromar** [comment]
Thanks. I've added a new emulator for up-to-date trinity DB.
So make sure to select Trinity 2019 in the top menu > Emulator. Otherwise it won't work for you.

You can download the new version here:
https://github.com/Nadromar/TrinityCreator/blob/master/TrinityCreatorSetup/bin/Release/TrinityCreatorSetup.msi

If something doesn't work, let me know.
