### ISSUE TITLE
How to make XP item ?

### ISSUE THREAD

**Issue by destrobg** [Nadromar/TrinityCreator#56]
How i can make item that gives xp for 80lvl ?

Consumable or whatever can be doned

**Comment by destrobg** [comment]
I mean how to add XP REWARD for quest

**Comment by Nadromar** [comment]
Missed this one, sorry about that.
You can select the XP for a quest under Rewards (the 8th group on the left)
You can't specify the amount of XP, if you want some massive XP solution, you may have to work with LUA.
There's possibly a better solution but, try asking on an emulator forum about it, they'll be able to help you better since this isn't really a TCreator issue.
