### ISSUE TITLE
db error

### ISSUE THREAD

**Issue by Tntdruid** [Nadromar/TrinityCreator#62]
Hello,

Getting this error:

Database Error: Unknown column 'Health_mod' in field list'

When saving a new NPC to the DB.

Using latest https://github.com/StygianTheBest/StygianCore#changelog) https://stygianthebest.github.io/

**Comment by Nadromar** [comment]
Probably based off an older version of trinity, which makes it not compatible.
But if you select AzerothCore it may work since it has a health_mod column.
Failing that, I can't help you right now but at some point in the future I'll add support to easily modify column names for different emulators.
Best of luck!

**Comment by Tntdruid** [comment]
Did that, did not work, thanks for your response.

Time to looks for a new wolk solo pack

**Comment by Tntdruid** [comment]
Added the Health_mod and Armor_mod to the db and it works now 👍
